version: 2

models:
  - name: session_summary
    description: "Summary of user sessions."
    columns:
      - name: sessionId
        description: "Unique identifier for each session."
        data_tests:
          - unique
          - not_null
